apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeapp
        image: 365825155295.dkr.ecr.us-east-1.amazonaws.com/node-app:main-c2a2fe4bf5-47
        ports:
        - containerPort: 3000
